FROM rust:1.87.0 AS builder
WORKDIR /usr/src/emissary

RUN apt-get update && apt-get install -y cmake git

RUN git clone https://github.com/altonen/emissary && \
  cd emissary && \
  cargo install --profile testnet --no-default-features --features web-ui --path emissary-cli

FROM debian:bookworm
RUN apt-get update && apt-get install -y libssl-dev && rm -rf /var/lib/apt/lists/*
COPY --from=builder /usr/local/cargo/bin/emissary-cli /usr/local/bin/emissary-cli

CMD ["emissary-cli"]
